#include "BIS_AddonInfo.hpp"
class CfgPatches
{
	class sl_animations
	{
		units[]={};
		weapons[]={};
		requiredVersion=0.0099999998;
		requiredAddons[]=
		{
			"A3_Anims_F",
			"A3_Anims_F_Config_Sdr"
		};
		version=1;
	};
};
class cfgFunctions
{
	class Love
	{
		class Authors
		{
			file="\sl_animations";
			class WeLikeAuthors
			{
				preinit=1;
			};
		};
	};
};
class CfgMovesBasic
{
	access=1;
	skeletonName="";
	collisionVertexPattern[]=
	{
		"1a",
		"2a",
		"3a",
		"4a",
		"5a",
		"6a",
		"7a",
		"8a",
		"9a",
		"10a",
		"11a",
		"12a",
		"13a",
		"14a",
		"15a",
		"16a",
		"17a",
		"18a",
		"19a",
		"20a",
		"21a",
		"22a",
		"23a",
		"24a",
		"25a",
		"26a",
		"27a",
		"28a",
		"29a",
		"30a",
		"31a",
		"32a",
		"33a",
		"34a",
		"1c",
		"2c",
		"3c",
		"4c",
		"5c",
		"6c",
		"7c",
		"8c"
	};
	collisionGeomCompPattern[]={1,3};
	class Default;
	class StandBase;
	class AmovPercMstpSnonWnonDnon: StandBase
	{
	};
	class AmovPpneMstpSnonWnonDnon: AmovPercMstpSnonWnonDnon
	{
	};
	class CL3_anim_AmovPpneMstpSnonWnonDnon: AmovPpneMstpSnonWnonDnon
	{
	};
	class DefaultDie;
	class ManActions
	{
		CL3_anim_ArrestedIn="CL3_anim_ArrestedIn";
		CL3_anim_ArrestedLoop="CL3_anim_ArrestedLoop";
		CL3_anim_ArrestedOut="CL3_anim_ArrestedOut";
		CL3_anim_ArrestedSit="CL3_anim_ArrestedSit";
		CL3_anim_ArrestedProne="CL3_anim_ArrestedProne";
		CL3_anim_codecrackerATM="CL3_anim_codecrackerATM";
		CL3_anim_drill_short="CL3_anim_drill_short";
		CL3_anim_managerdoorlockpick="CL3_anim_managerdoorlockpick";
		CL3_anim_placeC4[]=
		{
			"CL3_anim_placeC4",
			"Gesture"
		};
		CL3_anim_beartrap1="CL3_anim_beartrap1";
		CL3_anim_beartrap2="CL3_anim_beartrap2";
		CL3_anim_drink="CL3_anim_drink";
		CL3_anim_eat="CL3_anim_eat";
		BP_Act_Man_Drink_Erc_x3_Gesture[]=
		{
			"BP_Drink_Erc_x3_Gesture",
			"Gesture"
		};
		BP_Act_Man_Eat_Erc_x3_Gesture[]=
		{
			"BP_Eat_Erc_x3_Gesture",
			"Gesture"
		};
		CL3_anim_halt="CL3_anim_halt";
		cl3_nightclubdance="cl3_nightclubdance";
		cl3_dubstepdance="cl3_dubstepdance";
		cl3_crazydrunkdance="cl3_crazydrunkdance";
		cl3_dubstepPop="cl3_dubstepPop";
		cl3_DuoIvan="cl3_DuoIvan";
		cl3_DuoStephan="cl3_DuoStephan";
		cl3_hiphopdance="cl3_hiphopdance";
		cl3_robotdance="cl3_robotdance";
		cl3_russiandance="cl3_russiandance";
		cl3_Stephan="cl3_Stephan";
		CL3_anim_electric_chair="CL3_anim_electric_chair";
		CL3_FastRoping_animation="CL3_FastRoping_animation";
		cl_fishingrod_cast[]=
		{
			"cl_fishingrod_cast",
			"Gesture"
		};
		cl_fishingrod_strike[]=
		{
			"cl_fishingrod_strike",
			"Gesture"
		};
		CL3_anim_GatheringIn1="CL3_anim_GatheringIn1";
		CL3_anim_GatheringIn2="CL3_anim_GatheringIn2";
		CL3_anim_GatheringIn3="CL3_anim_GatheringIn3";
		CL3_anim_GatheringIn4="CL3_anim_GatheringIn4";
		CL3_anim_GatheringIn5="CL3_anim_GatheringIn5";
		CL3_anim_GatheringIn6="CL3_anim_GatheringIn6";
		CL3_anim_GatheringOut="CL3_anim_GatheringOut";
		CL3_anim_Gathering1="CL3_anim_Gathering1";
		CL3_anim_Gathering2="CL3_anim_Gathering2";
		CL3_anim_Gathering3="CL3_anim_Gathering3";
		CL3_anim_Gathering4="CL3_anim_Gathering4";
		CL3_anim_Gathering5="CL3_anim_Gathering5";
		CL3_anim_Gathering6="CL3_anim_Gathering6";
		cl3_anim_getmug="cl3_anim_getmug";
		CL3_anim_halt2="CL3_anim_halt2";
		CL3_anim_HandsUp="CL3_anim_HandsUp";
		CL3_anim_HandsLoop="CL3_anim_HandsLoop";
		CL3_anim_HandsDown="CL3_anim_HandsDown";
		CL3_anim_pron_grinder="CL3_anim_pron_grinder";
		CL3_anim_lockpick="CL3_anim_lockpick";
		CL3_anim_lunatic="CL3_anim_lunatic";
		cl3_bouncer="cl3_bouncer";
		cl3_bow_pray="cl3_bow_pray";
		cl3_clapping="cl3_clapping";
		cl3_hand_stand="cl3_hand_stand";
		cl3_muscle="cl3_muscle";
		cl3_pushups="cl3_pushups";
		cl3_violin="cl3_violin";
		cl3_wank="cl3_wank";
		cl3_yoyo="cl3_yoyo";
		cl3_middle_finger[]=
		{
			"cl3_middle_finger",
			"Gesture"
		};
		cl3_suck_it[]=
		{
			"cl3_suck_it",
			"Gesture"
		};
		cl3_thumbs_down[]=
		{
			"cl3_thumbs_down",
			"Gesture"
		};
		cl3_thumbs_up[]=
		{
			"cl3_thumbs_up",
			"Gesture"
		};
		cl3_wanker[]=
		{
			"cl3_wanker",
			"Gesture"
		};
		cl3_no_way[]=
		{
			"cl3_no_way",
			"Gesture"
		};
		cl3_yes[]=
		{
			"cl3_yes",
			"Gesture"
		};
		cl3_that_way[]=
		{
			"cl3_that_way",
			"Gesture"
		};
		cl3_hitchhiking[]=
		{
			"cl3_hitchhiking",
			"Gesture"
		};
		CL3_anim_mugpis="CL3_anim_mugpis";
		CL3_anim_mugrif="CL3_anim_mugrif";
		CL3_anim_Portaloo="CL3_anim_Portaloo";
		CL3_anim_Poo="CL3_anim_Poo";
		CL3_anim_Pee="CL3_anim_Pee";
		CL3_anim_Wank="CL3_anim_Wank";
		CL3_anim_pliers="CL3_anim_pliers";
		CL3_anim_PunchRandom="CL3_anim_PunchRandom";
		CL3_anim_Punch1="CL3_anim_Punch1";
		CL3_anim_Punch2="CL3_anim_Punch2";
		CL3_anim_Punch3="CL3_anim_Punch3";
		CL3_anim_Punch4="CL3_anim_Punch4";
		CL3_anim_Receive1a="CL3_anim_Receive1a";
		CL3_anim_Receive1b="CL3_anim_Receive1b";
		CL3_anim_Receive2a="CL3_anim_Receive2a";
		CL3_anim_Receive2b="CL3_anim_Receive2b";
		CL3_anim_Receive3a="CL3_anim_Receive3a";
		CL3_anim_Receive3b="CL3_anim_Receive3b";
		CL3_anim_Receive3c="CL3_anim_Receive3c";
		CL3_anim_Receive4="CL3_anim_Receive4";
		CL3_anim_Knockout1In="CL3_anim_Knockout1In";
		CL3_anim_Knockout1End="CL3_anim_Knockout1End";
		CL3_anim_Knockout2In="CL3_anim_Knockout2In";
		CL3_anim_Knockout2End="CL3_anim_Knockout2End";
		CL3_anim_WeaponHit="CL3_anim_WeaponHit";
		cl3_push_animation="cl3_push_animation";
		CL3_anim_RepairCrouch="CL3_anim_RepairCrouch";
		CL3_anim_surrenderstart="CL3_anim_surrenderstart";
		CL3_anim_surrenderloop="CL3_anim_surrenderloop";
		CL3_anim_surrenderfinish="CL3_anim_surrenderfinish";
		CL3_anim_Ticket="CL3_anim_Ticket";
		CL3_anim_Shovel="CL3_anim_Shovel";
		CL3_anim_Hammer[]=
		{
			"CL3_anim_Hammer",
			"Gesture"
		};
		CRPTHSForward[]=
		{
			"CRPTHSForward",
			"Gesture"
		};
		CRPTHSStop[]=
		{
			"CRPTHSStop",
			"Gesture"
		};
		CRPTHSCover[]=
		{
			"CRPTHSCover",
			"Gesture"
		};
		CRPTHSRegroup[]=
		{
			"CRPTHSRegroup",
			"Gesture"
		};
		CRPTHSEngage[]=
		{
			"CRPTHSEngage",
			"Gesture"
		};
		CRPTHSPoint[]=
		{
			"CRPTHSPoint",
			"Gesture"
		};
		CRPTHSHold[]=
		{
			"CRPTHSHold",
			"Gesture"
		};
		CRPTHSWarning[]=
		{
			"CRPTHSWarning",
			"Gesture"
		};
		CRPTHSForwardStandLowered[]=
		{
			"CRPTHSForwardStandLowered",
			"Gesture"
		};
		CRPTHSStopStandLowered[]=
		{
			"CRPTHSStopStandLowered",
			"Gesture"
		};
		CRPTHSCoverStandLowered[]=
		{
			"CRPTHSCoverStandLowered",
			"Gesture"
		};
		CRPTHSRegroupStandLowered[]=
		{
			"CRPTHSRegroupStandLowered",
			"Gesture"
		};
		CRPTHSEngageStandLowered[]=
		{
			"CRPTHSEngageStandLowered",
			"Gesture"
		};
		CRPTHSPointStandLowered[]=
		{
			"CRPTHSPointStandLowered",
			"Gesture"
		};
		CRPTHSHoldStandLowered[]=
		{
			"CRPTHSHoldStandLowered",
			"Gesture"
		};
		CRPTHSWarningStandLowered[]=
		{
			"CRPTHSWarningStandLowered",
			"Gesture"
		};
	};
	class Actions
	{
		class NoActions: ManActions
		{
		};
	};
};
class CfgMovesMaleSdr: CfgMovesBasic
{
	skeletonName="OFP2_ManSkeleton";
	gestures="CfgGesturesMale";
	class States
	{
		class AinvPknlMstpSnonWnonDnon_medic;
		class AmovPpneMstpSnonWnonDnon;
		class AmovPercMstpSnonWnonDnon_falling;
		class Crew;
		class CutSceneAnimationBase;
		class AidlPercMstpSrasWrflDnon_AI;
		class AmovPercMstpSlowWrflDnon;
		class AmovPercMstpSnonWnonDnon;
		class ActsPsitMstpSnonWunaDnon_sceneNikitinDisloyalty_Cooper: CutSceneAnimationBase
		{
			speed=0.00771;
			file="\sl_animations\ip_a2c\anims\ActsPsitMstpSnonWunaDnon_sceneNikitinDisloyalty_Cooper";
			looped=0;
			actions="RifleLowStandActions";
			disableWeapons=1;
			enableOptics=0;
			enableBinocular=0;
			canPullTrigger=0;
			headBobMode=0;
			headBobStrength=0;
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.0099999998
			};
			InterpolateTo[]={};
		};
		/*class AmovPercMstpSnonWnonDnon_exerciseKata: CutSceneAnimationBase
		{
			file="\sl_animations\ip_a2c\anims\AmovPercMstpSnonWnonDnon_exerciseKata.rtm";
			speed=0.029999999;
			canPullTrigger=0;
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				2,
				"AmovPercMstpSnonWnonDnon_exerciseKata",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.0099999998
			};
		};*/
		class ActsPknlMstpSnonWnonDnon_TreatingInjured_NikitinDead: CutSceneAnimationBase
		{
			file="\sl_animations\ip_a2c\anims\ActsPknlMstpSnonWnonDnon_TreatingInjured.rtm";
			speed=0.025;
			enableBinocular=0;
			canPullTrigger=0;
			ConnectTo[]=
			{
				"AdthPercMstpSrasWrflDnon_NikitinDead2",
				0.0099999998
			};
			InterpolateTo[]=
			{
				"AdthPercMstpSrasWrflDnon_NikitinDead2",
				0.0099999998
			};
		};
		class AdthPercMstpSrasWrflDnon_NikitinDead2: ActsPknlMstpSnonWnonDnon_TreatingInjured_NikitinDead
		{
			file="\sl_animations\ip_a2c\anims\AdthPercMstpSrasWrflDnon_NikitinDead.rtm";
			speed=1.05;
			looped=0;
			terminal=0;
			ConnectTo[]={};
			InterpolateTo[]={};
		};
		class CL3_anim_ArrestedIn: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\sl_animations\arrest\anims\ArrestedIn.rtm";
			speed=-3;
			looped=0;
			soundEnabled=0;
			duty=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]=
			{
				"CL3_anim_ArrestedLoop",
				0.1
			};
			InterpolateTo[]=
			{
				"CL3_anim_ArrestedLoop",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_ArrestedLoop: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\sl_animations\arrest\anims\ArrestedLoop.rtm";
			speed=1e+010;
			looped=0;
			duty=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"CL3_anim_ArrestedOut",
				0.1,
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_ArrestedOut: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\sl_animations\arrest\anims\ArrestedOut.rtm";
			speed=-3;
			looped=0;
			duty=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_ArrestedProne: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\sl_animations\arrest\anims\ArrestedProne.rtm";
			speed=1e+010;
			looped=0;
			duty=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_ArrestedSit: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\sl_animations\arrest\anims\ArrestedSit.rtm";
			speed=1e+010;
			looped=0;
			duty=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_codecrackerATM: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-15;
			file="\sl_animations\bank\anim\codecrackerATM.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.80000001,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_drill_short: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-2.3;
			file="\sl_animations\bank\anim\drill_short.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.80000001,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_managerdoorlockpick: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-14;
			file="\sl_animations\bank\anim\managerdoorlockpick.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.80000001,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_beartrap1: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-4;
			file="\sl_animations\beartrap\anims\beartrap1.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			connectTo[]=
			{
				"CL3_anim_beartrap2",
				0.1
			};
			InterpolateTo[]=
			{
				"CL3_anim_beartrap2",
				0.2,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_beartrap2: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-20;
			file="\sl_animations\beartrap\anims\beartrap2.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			connectTo[]=
			{
				"AmovPpneMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPpneMstpSnonWnonDnon",
				0.60000002,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_drink: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-6;
			file="\sl_animations\consumables\anims\drinking.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"CL3_anim_beartrap2",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_eat: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-11;
			file="\sl_animations\consumables\anims\eating.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_halt: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-15;
			file="\sl_animations\CopActions\anims\halt.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"CL3_anim_beartrap2",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class cl3_nightclubdance: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-75.699997;
			file="\sl_animations\dance\anims\nightclubdance.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5,
				"Unconscious",
				0.2
			};
			InterpolateFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5
			};
		};
		class cl3_dubstepdance: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-42.799999;
			file="\sl_animations\dance\anims\dubstepdance.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5,
				"Unconscious",
				0.2
			};
			InterpolateFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5
			};
		};
		class cl3_crazydrunkdance: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-73.699997;
			file="\sl_animations\dance\anims\crazydrunkdance.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5,
				"Unconscious",
				0.2
			};
			InterpolateFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5
			};
		};
		class cl3_dubstepPop: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-26.799999;
			file="\sl_animations\dance\anims\dubstepPop.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5,
				"Unconscious",
				0.2
			};
			InterpolateFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5
			};
		};
		class cl3_DuoIvan: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-39.299999;
			file="\sl_animations\dance\anims\DuoIvan.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5,
				"Unconscious",
				0.2
			};
			InterpolateFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5
			};
		};
		class cl3_DuoStephan: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-39.299999;
			file="\sl_animations\dance\anims\DuoStephan.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5,
				"Unconscious",
				0.2
			};
			InterpolateFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5
			};
		};
		class cl3_hiphopdance: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-76;
			file="\sl_animations\dance\anims\hiphopdance.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5,
				"Unconscious",
				0.2
			};
			InterpolateFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5
			};
		};
		class cl3_robotdance: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-134;
			file="\sl_animations\dance\anims\robotdance.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5,
				"Unconscious",
				0.2
			};
			InterpolateFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5
			};
		};
		class cl3_russiandance: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-32.299999;
			file="\sl_animations\dance\anims\russiandance.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5,
				"Unconscious",
				0.2
			};
			InterpolateFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5
			};
		};
		class cl3_Stephan: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-96.300003;
			file="\sl_animations\dance\anims\Stephan.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5,
				"Unconscious",
				0.2
			};
			InterpolateFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5
			};
		};
		class CL3_anim_electric_chair: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-7.5999999;
			file="\sl_animations\electric_chair\anims\electric_chairing.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class CL3_FastRoping_animation: Crew
		{
			file="\sl_animations\fastrope\FastRoping_animation.rtm";
			interpolateTo[]=
			{
				"Unconscious",
				1
			};
		};
		class CL3_anim_GatheringIn1: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=0.55000001;
			file="\sl_animations\gathering\anims\CL3_anim_GatheringIn.rtm";
			looped=0;
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"CL3_anim_Gathering1",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_GatheringIn2: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=0.55000001;
			file="\sl_animations\gathering\anims\CL3_anim_GatheringIn.rtm";
			looped=0;
			soundEnabled=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"CL3_anim_Gathering2",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_GatheringIn3: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=0.55000001;
			file="\sl_animations\gathering\anims\CL3_anim_GatheringIn.rtm";
			looped=0;
			soundEnabled=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"CL3_anim_Gathering3",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_GatheringIn4: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=0.55000001;
			file="\sl_animations\gathering\anims\CL3_anim_GatheringIn.rtm";
			looped=0;
			soundEnabled=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"CL3_anim_Gathering4",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_GatheringIn5: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=0.55000001;
			file="\sl_animations\gathering\anims\CL3_anim_GatheringIn.rtm";
			looped=0;
			soundEnabled=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"CL3_anim_Gathering5",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_GatheringIn6: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=0.55000001;
			file="\sl_animations\gathering\anims\CL3_anim_GatheringIn.rtm";
			looped=0;
			soundEnabled=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"CL3_anim_Gathering6",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_Gathering1: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=0.20999999;
			file="\sl_animations\gathering\anims\CL3_anim_Gathering1.rtm";
			looped=0;
			soundEnabled=0;
			canBlendStep=0;
			ConnectTo[]=
			{
				"CL3_anim_GatheringOut",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_Gathering2: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=0.17;
			file="\sl_animations\gathering\anims\CL3_anim_Gathering2.rtm";
			looped=0;
			soundEnabled=0;
			canBlendStep=0;
			ConnectTo[]=
			{
				"CL3_anim_GatheringOut",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_Gathering3: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=0.14;
			file="\sl_animations\gathering\anims\CL3_anim_Gathering3.rtm";
			looped=0;
			soundEnabled=0;
			canBlendStep=0;
			ConnectTo[]=
			{
				"CL3_anim_GatheringOut",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_Gathering4: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=0.090000004;
			file="\sl_animations\gathering\anims\CL3_anim_Gathering4.rtm";
			looped=0;
			soundEnabled=0;
			canBlendStep=0;
			ConnectTo[]=
			{
				"CL3_anim_GatheringOut",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_Gathering5: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=0.17;
			canBlendStep=0;
			file="\sl_animations\gathering\anims\CL3_anim_Gathering5.rtm";
			looped=0;
			soundEnabled=0;
			ConnectTo[]=
			{
				"CL3_anim_GatheringOut",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_Gathering6: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			speed=0.15000001;
			canBlendStep=0;
			forceAim=1;
			file="\sl_animations\gathering\anims\CL3_anim_Gathering6.rtm";
			looped=0;
			soundEnabled=0;
			ConnectTo[]=
			{
				"CL3_anim_GatheringOut",
				0.1
			};
			InterpolateTo[]={};
		};
		class CL3_anim_GatheringOut: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			canBlendStep=0;
			minPlayTime=1;
			speed=0.55000001;
			file="\sl_animations\gathering\anims\CL3_anim_GatheringOut.rtm";
			looped=0;
			soundEnabled=0;
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class cl3_anim_getmug: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-14;
			file="\sl_animations\getmug\anims\cl3_anim_getmug.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_halt2: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-13;
			file="\sl_animations\halt\anims\cl3_anims_halt.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_HandsUp: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\sl_animations\HandsUp\anims\HandsUp.rtm";
			speed=0.64999998;
			looped=0;
			soundEnabled=0;
			duty=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]=
			{
				"CL3_anim_HandsLoop",
				0.1
			};
			InterpolateTo[]=
			{
				"CL3_anim_HandsLoop",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_HandsLoop: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\sl_animations\HandsUp\anims\HandsLoop.rtm";
			speed=1e+010;
			looped=0;
			soundEnabled=0;
			duty=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"CL3_anim_HandsDown",
				0.1,
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_HandsDown: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\sl_animations\HandsUp\anims\HandsDown.rtm";
			speed=0.69999999;
			looped=0;
			duty=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_pron_grinder: AmovPpneMstpSnonWnonDnon
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-14.602;
			file="\sl_animations\Jail\anims\pron_grinder.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPpneMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPpneMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_lockpick: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-7.5999999;
			file="\sl_animations\Lockpicking\anims\lockpicking.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_lunatic: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-15;
			file="\sl_animations\mastlun\anims\CL3_anim_lunatic.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class cl3_bouncer: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-13.7;
			file="\sl_animations\menu_gestures\anims\bouncer.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5,
				"Unconscious",
				0.2
			};
			InterpolateFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5
			};
		};
		class cl3_bow_pray: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-15.8;
			file="\sl_animations\menu_gestures\anims\bow_pray.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5,
				"Unconscious",
				0.2
			};
			InterpolateFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5
			};
		};
		class cl3_clapping: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-10.7;
			file="\sl_animations\menu_gestures\anims\clapping.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5,
				"Unconscious",
				0.2
			};
			InterpolateFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5
			};
		};
		class cl3_hand_stand: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-7;
			file="\sl_animations\menu_gestures\anims\hand_stand.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5,
				"Unconscious",
				0.2
			};
			InterpolateFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5
			};
		};
		class cl3_muscle: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-10.3;
			file="\sl_animations\menu_gestures\anims\muscle.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5,
				"Unconscious",
				0.2
			};
			InterpolateFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5
			};
		};
		class cl3_pushups: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-10;
			file="\sl_animations\menu_gestures\anims\pushups.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5,
				"Unconscious",
				0.2
			};
			InterpolateFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5
			};
		};
		class cl3_violin: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-13;
			file="\sl_animations\menu_gestures\anims\violin.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5,
				"Unconscious",
				0.2
			};
			InterpolateFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5
			};
		};
		class cl3_wank: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-7.3000002;
			file="\sl_animations\menu_gestures\anims\wank.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5,
				"Unconscious",
				0.2
			};
			InterpolateFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5
			};
		};
		class cl3_yoyo: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-20.299999;
			file="\sl_animations\menu_gestures\anims\yoyo.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5,
				"Unconscious",
				0.2
			};
			InterpolateFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.5
			};
		};
		class CL3_anim_mugpis: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-7;
			file="\sl_animations\mugpis\anims\CL3_anim_mugpis.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_mugrif: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-9;
			file="\sl_animations\mugrif\anims\CL3_anim_mugrif.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_Portaloo: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\sl_animations\naturescall\anims\Portaloo.rtm";
			speed=-30;
			looped=0;
			soundEnabled=0;
			duty=0;
			disableWeapons=0;
			minPlayTime=1;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_Poo: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\sl_animations\naturescall\anims\shittingout.rtm";
			speed=-30;
			looped=0;
			duty=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_Pee: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\sl_animations\naturescall\anims\pissing.rtm";
			speed=-10;
			looped=0;
			duty=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_Wank: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\sl_animations\naturescall\anims\wanking.rtm";
			speed=-6;
			looped=0;
			duty=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_pliers: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=0.188757;
			file="\sl_animations\pliers\anims\pliers.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_PunchRandom: AinvPknlMstpSnonWnonDnon_medic
		{
			variantsPlayer[]=
			{
				"CL3_anim_Punch1",
				0.25,
				"CL3_anim_Punch2",
				0.25,
				"CL3_anim_Punch3",
				0.25,
				"CL3_anim_Punch4",
				0.25
			};
			variantAfter[]={1,5,10};
			speed=0.55000001;
			file="\sl_animations\punch\anims\Punch1.rtm";
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateFrom[]=
			{
				"AmovPercMstpSrasWpstDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_Punch1: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\sl_animations\punch\anims\Punch1.rtm";
			speed=0.55000001;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_Punch2: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\sl_animations\punch\anims\Punch2.rtm";
			speed=0.55000001;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_Punch3: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\sl_animations\punch\anims\Punch3.rtm";
			speed=0.55000001;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_Punch4: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\sl_animations\punch\anims\Punch4.rtm";
			speed=0.55000001;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_Receive1a: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\sl_animations\punch\anims\Receive1a.rtm";
			speed=0.30000001;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_Receive1b: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\sl_animations\punch\anims\Receive1b.rtm";
			speed=0.30000001;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_Receive2a: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\sl_animations\punch\anims\Receive2a.rtm";
			speed=0.30000001;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_Receive2b: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\sl_animations\punch\anims\Receive2b.rtm";
			speed=0.30000001;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_Receive3a: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\sl_animations\punch\anims\Receive3a.rtm";
			speed=0.44999999;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_Receive3b: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\sl_animations\punch\anims\Receive3b.rtm";
			speed=0.30000001;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_Receive3c: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\sl_animations\punch\anims\Receive3c.rtm";
			speed=0.30000001;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_Receive4: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\sl_animations\punch\anims\Receive4.rtm";
			speed=0.30000001;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_Knockout1In: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\sl_animations\punch\anims\KnockOut1In.rtm";
			speed=0.27000001;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"CL3_anim_Knockout1End",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_Knockout1End: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\sl_animations\punch\anims\KnockOut1End.rtm";
			speed=0.27000001;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_Knockout2In: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\sl_animations\punch\anims\KnockOut2In.rtm";
			speed=0.30000001;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"CL3_anim_Knockout2End",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_Knockout2End: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\sl_animations\punch\anims\KnockOut2End.rtm";
			speed=0.25;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_WeaponHit: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\sl_animations\punch\anims\WeaponHit.rtm";
			speed=0.25;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class cl3_push_animation: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-0.69999999;
			file="\sl_animations\push\anims\push.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_RepairCrouch: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-27;
			file="\sl_animations\repair\anims\CL3_anim_RepairCrouch.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class cl3_smoke_cig_anim: CutSceneAnimationBase
		{
			file="\sl_animations\smoke\smoke.rtm";
			speed=0.188757;
			boundingSphere=4;
			collisionShape="A3\anims_f\Data\Geom\Sdr\geom_empty.p3d";
			ConnectTo[]={};
			InterpolateTo[]={};
		};
		class CL3_anim_surrenderstart: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\sl_animations\surrender\anims\surrenderstart.rtm";
			speed=-3;
			looped=0;
			soundEnabled=0;
			duty=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]=
			{
				"CL3_anim_surrenderloop",
				0.1
			};
			InterpolateTo[]=
			{
				"CL3_anim_surrenderloop",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_surrenderLoop: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\sl_animations\surrender\anims\surrenderloop.rtm";
			speed=1e+010;
			looped=0;
			soundEnabled=0;
			duty=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"CL3_anim_surrenderfinish",
				0.1,
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_surrenderfinish: AinvPknlMstpSnonWnonDnon_medic
		{
			file="\sl_animations\surrender\anims\surrenderfinish.rtm";
			speed=-2;
			looped=0;
			duty=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSnonWnonDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_Ticket: AmovPercMstpSnonWnonDnon_falling
		{
			variantsPlayer[]={};
			forceAim=1;
			speed=-8;
			file="\sl_animations\ticket\anims\CL3_anim_ticket.rtm";
			looped=0;
			minPlayTime=1;
			disableWeapons=0;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			soundEnabled=0;
			canBlendStep=0;
			ConnectFrom[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.1
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.2
			};
		};
		class CL3_anim_Shovel: AidlPercMstpSrasWrflDnon_AI
		{
			file="\sl_animations\tools\anims\Shovel.rtm";
			speed=-6;
			looped=0;
			soundEnabled=0;
			disableWeapons=0;
			minPlayTime=1;
			ignoreMinPlayTime[]=
			{
				"Unconscious"
			};
			ConnectTo[]={};
			InterpolateTo[]=
			{
				"AmovPercMstpSlowWrflDnon",
				0.1,
				"AmovPercMstpSrasWpstDnon",
				0.1,
				"Unconscious",
				0.2
			};
		};
	};
};
class CfgGesturesMale
{
	class Default;
	class States
	{
		class CRPTHSBase: Default
		{
			canPullTrigger=0;
			connectAs="";
			connectFrom[]={};
			connectTo[]={};
			disableWeapons=0;
			enableBinocular=1;
			enableMissile=1;
			enableOptics=0;
			equivalentTo="";
			file="\A3\anims_f\Data\Anim\Sdr\gst\GestureHi.rtm";
			forceAim=0;
			headBobMode=0;
			headBobStrength=0;
			interpolateFrom[]={};
			interpolateTo[]={};
			interpolateWith[]={};
			interpolationRestart=0;
			interpolationSpeed=6;
			looped=0;
			mask="CRPTHSLeftArm";
			minPlayTime=0.5;
			preload=0;
			ragdoll=0;
			relSpeedMax=1;
			relSpeedMin=1;
			showHandGun=0;
			showItemInHand=0;
			showItemInRightHand=0;
			showWeaponAim=1;
			soundEdge[]={0.5,1};
			soundEnabled=1;
			soundOverride="";
			speed=-2;
			static=0;
			terminal=0;
			Walkcycles=1;
			weaponIK=1;
			leftHandIKBeg=1;
			leftHandIKCurve[]={0,1,0.1,0,0.80000001,0,1,1};
			leftHandIKEnd=1;
			rightHandIKBeg=1;
			rightHandIKCurve[]={1};
			rightHandIKEnd=1;
		};
		class CRPTHSForward: CRPTHSBase
		{
			file="\sl_animations\hand_signals\anims\crp_ths_forward.rtm";
			speed=1;
		};
		class CRPTHSForwardStandLowered: CRPTHSForward
		{
			file="\sl_animations\hand_signals\anims\crp_ths_forward_stand_lowered.rtm";
		};
		class CRPTHSStop: CRPTHSForward
		{
			file="\sl_animations\hand_signals\anims\crp_ths_stop.rtm";
			speed=0.60000002;
		};
		class CRPTHSStopStandLowered: CRPTHSStop
		{
			file="\sl_animations\hand_signals\anims\crp_ths_stop_stand_lowered.rtm";
		};
		class CRPTHSCover: CRPTHSForward
		{
			file="\sl_animations\hand_signals\anims\crp_ths_cover.rtm";
			speed=0.80000001;
		};
		class CRPTHSCoverStandLowered: CRPTHSCover
		{
			file="\sl_animations\hand_signals\anims\crp_ths_cover_stand_lowered.rtm";
		};
		class CRPTHSRegroup: CRPTHSForward
		{
			file="\sl_animations\hand_signals\anims\crp_ths_regroup.rtm";
			speed=0.80000001;
		};
		class CRPTHSRegroupStandLowered: CRPTHSRegroup
		{
			file="\sl_animations\hand_signals\anims\crp_ths_regroup_stand_lowered.rtm";
		};
		class CRPTHSEngage: CRPTHSForward
		{
			file="\sl_animations\hand_signals\anims\crp_ths_engage.rtm";
			speed=0.89999998;
		};
		class CRPTHSEngageStandLowered: CRPTHSEngage
		{
			file="\sl_animations\hand_signals\anims\crp_ths_engage_stand_lowered.rtm";
		};
		class CRPTHSPoint: CRPTHSForward
		{
			file="\sl_animations\hand_signals\anims\crp_ths_point.rtm";
			speed=0.80000001;
		};
		class CRPTHSPointStandLowered: CRPTHSPoint
		{
			file="\sl_animations\hand_signals\anims\crp_ths_point_stand_lowered.rtm";
		};
		class CRPTHSHold: CRPTHSForward
		{
			file="\sl_animations\hand_signals\anims\crp_ths_hold.rtm";
			speed=0.80000001;
		};
		class CRPTHSHoldStandLowered: CRPTHSHold
		{
			file="\sl_animations\hand_signals\anims\crp_ths_hold_stand_lowered.rtm";
		};
		class CRPTHSWarning: CRPTHSForward
		{
			file="\sl_animations\hand_signals\anims\crp_ths_warning.rtm";
			speed=0.80000001;
		};
		class CRPTHSWarningStandLowered: CRPTHSWarning
		{
			file="\sl_animations\hand_signals\anims\crp_ths_warning_stand_lowered.rtm";
		};
		class BP_Drink_Erc_x3_Gesture: Default
		{
			file="\sl_animations\BP\anims\BP_Drink_Erc_x3_Gesture.rtm";
			looped=0;
			speed=0.1;
			duty=0;
			aimingBody="aimingUpDefault";
			mask="LeftHandFeed";
			leftHandIKBeg=0;
			leftHandIKCurve[]={};
			leftHandIKEnd=1;
			rightHandIKBeg=1;
			rightHandIKCurve[]={};
			rightHandIKEnd=1;
			weaponIK=1;
			enableOptics=0;
			showWeaponAim=0;
			disableWeapons=0;
			disableWeaponsLong=0;
			canPullTrigger=1;
			InterpolateTo[]={};
			interpolateFrom[]={};
			soundOverride="";
		};
		class BP_Eat_Erc_x3_Gesture: Default
		{
			file="\sl_animations\BP\anims\BP_Eat_Erc_x3_Gesture.rtm";
			looped=0;
			speed=0.1;
			duty=0;
			aimingBody="aimingUpDefault";
			mask="LeftHandFeed";
			leftHandIKBeg=0;
			leftHandIKCurve[]={};
			leftHandIKEnd=1;
			rightHandIKBeg=1;
			rightHandIKCurve[]={};
			rightHandIKEnd=1;
			weaponIK=1;
			enableOptics=0;
			showWeaponAim=0;
			disableWeapons=0;
			disableWeaponsLong=0;
			canPullTrigger=1;
			InterpolateTo[]={};
			interpolateFrom[]={};
			soundOverride="";
		};
		class CL3_anim_placec4: Default
		{
			file="\sl_animations\bank\anim\placec4.rtm";
			looped=0;
			speed=-1;
			mask="placeC4";
			rightHandIKCurve[]={1};
			leftHandIKCurve[]={0};
		};
		class cl_fishingrod_cast: Default
		{
			file="\sl_animations\fishingrod\anims\fishrodcast.rtm";
			looped=0;
			speed=-1.3;
			mask="FishingRodMask";
		};
		class cl_fishingrod_strike: Default
		{
			file="\sl_animations\fishingrod\anims\fishrodstrike.rtm";
			looped=0;
			speed=-1;
			mask="FishingRodMask";
		};
		class cl3_middle_finger: Default
		{
			file="\sl_animations\menu_gestures\anims\middle_finger.rtm";
			looped=0;
			speed=-2;
			mask="suckIT";
			rightHandIKCurve[]={1};
			leftHandIKCurve[]={0};
		};
		class cl3_suck_it: Default
		{
			file="\sl_animations\menu_gestures\anims\suck_it.rtm";
			looped=0;
			speed=-8.5;
			mask="suckIT";
			rightHandIKCurve[]={1};
			leftHandIKCurve[]={0};
		};
		class cl3_thumbs_down: Default
		{
			file="\sl_animations\menu_gestures\anims\cl3_thumbs_down.rtm";
			looped=0;
			speed=-4;
			mask="suckIT";
			rightHandIKCurve[]={1};
			leftHandIKCurve[]={0};
		};
		class cl3_thumbs_up: Default
		{
			file="\sl_animations\menu_gestures\anims\cl3_thumbs_up.rtm";
			looped=0;
			speed=-4;
			mask="suckIT";
			rightHandIKCurve[]={1};
			leftHandIKCurve[]={0};
		};
		class cl3_wanker: Default
		{
			file="\sl_animations\menu_gestures\anims\wanker.rtm";
			looped=0;
			speed=-4;
			mask="suckIT";
			rightHandIKCurve[]={1};
			leftHandIKCurve[]={0};
		};
		class cl3_no_way: Default
		{
			file="\sl_animations\menu_gestures\anims\no_way.rtm";
			looped=0;
			speed=-2.5999999;
			mask="suckIT";
			rightHandIKCurve[]={1};
			leftHandIKCurve[]={0};
		};
		class cl3_yes: Default
		{
			file="\sl_animations\menu_gestures\anims\yes.rtm";
			looped=0;
			speed=-2.5999999;
			mask="suckIT";
			rightHandIKCurve[]={1};
			leftHandIKCurve[]={0};
		};
		class cl3_that_way: Default
		{
			file="\sl_animations\menu_gestures\anims\that_way.rtm";
			looped=0;
			speed=-4.1999998;
			mask="suckIT";
			rightHandIKCurve[]={1};
			leftHandIKCurve[]={0};
		};
		class cl3_hitchhiking: Default
		{
			file="\sl_animations\menu_gestures\anims\hitchhiking.rtm";
			looped=0;
			speed=-4.5;
			mask="suckIT";
			rightHandIKCurve[]={1};
			leftHandIKCurve[]={0};
		};
		class CL3_anim_Hammer: Default
		{
			file="\sl_animations\tools\anims\hammergather.rtm";
			looped=0;
			speed=-6;
			mask="handsWeapon";
		};
	};
	class BlendAnims
	{
		class MaskStart
		{
			weight=0.85000002;
		};
		empty[]={};
		placeC4[]=
		{
			"LeftShoulder",
			1,
			"LeftArm",
			1,
			"LeftArmRoll",
			1,
			"LeftForeArm",
			1,
			"LeftForeArmRoll",
			1,
			"LeftHand",
			1,
			"LeftHandRing",
			1,
			"LeftHandPinky1",
			1,
			"LeftHandPinky2",
			1,
			"LeftHandPinky3",
			1,
			"LeftHandRing1",
			1,
			"LeftHandRing2",
			1,
			"LeftHandRing3",
			1,
			"LeftHandMiddle1",
			1,
			"LeftHandMiddle2",
			1,
			"LeftHandMiddle3",
			1,
			"LeftHandIndex1",
			1,
			"LeftHandIndex2",
			1,
			"LeftHandIndex3",
			1,
			"LeftHandThumb1",
			1,
			"LeftHandThumb2",
			1,
			"LeftHandThumb3",
			1,
			"Pelvis",
			1,
			"LeftLeg",
			1,
			"LeftLegRoll",
			1,
			"LeftUpLeg",
			1,
			"LeftUpLegRoll",
			1,
			"LeftFoot",
			1,
			"LeftToeBase",
			1,
			"RightLeg",
			1,
			"RightLegRoll",
			1,
			"RightUpLeg",
			1,
			"RightUpLegRoll",
			1,
			"RightFoot",
			1,
			"RightToeBase",
			1
		};
		FishingRodMask[]=
		{
			"weapon",
			1,
			"LeftShoulder",
			1,
			"LeftArm",
			1,
			"LeftArmRoll",
			1,
			"LeftForeArm",
			1,
			"LeftForeArmRoll",
			1,
			"LeftHand",
			1,
			"LeftHandRing",
			1,
			"LeftHandPinky1",
			1,
			"LeftHandPinky2",
			1,
			"LeftHandPinky3",
			1,
			"LeftHandRing1",
			1,
			"LeftHandRing2",
			1,
			"LeftHandRing3",
			1,
			"LeftHandMiddle1",
			1,
			"LeftHandMiddle2",
			1,
			"LeftHandMiddle3",
			1,
			"LeftHandIndex1",
			1,
			"LeftHandIndex2",
			1,
			"LeftHandIndex3",
			1,
			"LeftHandThumb1",
			1,
			"LeftHandThumb2",
			1,
			"LeftHandThumb3",
			1,
			"RightShoulder",
			1,
			"RightArm",
			1,
			"RightArmRoll",
			1,
			"RightForeArm",
			1,
			"RightForeArmRoll",
			1,
			"RightHand",
			1,
			"RightHandRing",
			1,
			"RightHandPinky1",
			1,
			"RightHandPinky2",
			1,
			"RightHandPinky3",
			1,
			"RightHandRing1",
			1,
			"RightHandRing2",
			1,
			"RightHandRing3",
			1,
			"RightHandMiddle1",
			1,
			"RightHandMiddle2",
			1,
			"RightHandMiddle3",
			1,
			"RightHandIndex1",
			1,
			"RightHandIndex2",
			1,
			"RightHandIndex3",
			1,
			"RightHandThumb1",
			1,
			"RightHandThumb2",
			1,
			"RightHandThumb3",
			1,
			"MaskStart"
		};
		suckIT[]=
		{
			"head",
			0.89999998,
			"neck1",
			0.80000001,
			"neck",
			0.69999999,
			"RightShoulder",
			1,
			"RightArm",
			1,
			"RightArmRoll",
			1,
			"RightForeArm",
			1,
			"RightForeArmRoll",
			1,
			"RightHand",
			1,
			"RightHandRing",
			1,
			"RightHandPinky1",
			1,
			"RightHandPinky2",
			1,
			"RightHandPinky3",
			1,
			"RightHandRing1",
			1,
			"RightHandRing2",
			1,
			"RightHandRing3",
			1,
			"RightHandMiddle1",
			1,
			"RightHandMiddle2",
			1,
			"RightHandMiddle3",
			1,
			"RightHandIndex1",
			1,
			"RightHandIndex2",
			1,
			"RightHandIndex3",
			1,
			"RightHandThumb1",
			1,
			"RightHandThumb2",
			1,
			"RightHandThumb3",
			1,
			"LeftShoulder",
			1,
			"LeftArm",
			1,
			"LeftArmRoll",
			1,
			"LeftForeArm",
			1,
			"LeftForeArmRoll",
			1,
			"LeftHand",
			1,
			"LeftHandRing",
			1,
			"LeftHandPinky1",
			1,
			"LeftHandPinky2",
			1,
			"LeftHandPinky3",
			1,
			"LeftHandRing1",
			1,
			"LeftHandRing2",
			1,
			"LeftHandRing3",
			1,
			"LeftHandMiddle1",
			1,
			"LeftHandMiddle2",
			1,
			"LeftHandMiddle3",
			1,
			"LeftHandIndex1",
			1,
			"LeftHandIndex2",
			1,
			"LeftHandIndex3",
			1,
			"LeftHandThumb1",
			1,
			"LeftHandThumb2",
			1,
			"LeftHandThumb3",
			1,
			"Spine",
			0.1,
			"Spine1",
			0.2,
			"Spine2",
			0.40000001,
			"Spine3",
			0.60000002
		};
		CRPTHSLeftArm[]=
		{
			"LeftShoulder",
			1,
			"LeftArm",
			1,
			"LeftArmRoll",
			1,
			"LeftForeArm",
			1,
			"LeftForeArmRoll",
			1,
			"LeftHand",
			1,
			"LeftHandIndex1",
			1,
			"LeftHandIndex2",
			1,
			"LeftHandIndex3",
			1,
			"LeftHandMiddle1",
			1,
			"LeftHandMiddle2",
			1,
			"LeftHandMiddle3",
			1,
			"LeftHandPinky1",
			1,
			"LeftHandMiddle2",
			1,
			"LeftHandMiddle3",
			1,
			"LeftHandPinky1",
			1,
			"LeftHandPinky2",
			1,
			"LeftHandPinky3",
			1,
			"LeftHandRing",
			1,
			"LeftHandRing1",
			1,
			"LeftHandRing2",
			1,
			"LeftHandRing3",
			1,
			"LeftHandThumb1",
			1,
			"LeftHandThumb2",
			1,
			"LeftHandThumb3",
			1
		};
		aimingUpDefault[]=
		{
			"weapon",
			1,
			"Camera",
			1,
			"launcher",
			1,
			"Head",
			1,
			"Neck",
			1,
			"Neck1",
			1,
			"LeftShoulder",
			1,
			"LeftArm",
			1,
			"LeftArmRoll",
			1,
			"LeftForeArm",
			1,
			"LeftForeArmRoll",
			1,
			"LeftHand",
			1,
			"LeftHandRing",
			1,
			"LeftHandPinky1",
			1,
			"LeftHandPinky2",
			1,
			"LeftHandPinky3",
			1,
			"LeftHandRing1",
			1,
			"LeftHandRing2",
			1,
			"LeftHandRing3",
			1,
			"LeftHandMiddle1",
			1,
			"LeftHandMiddle2",
			1,
			"LeftHandMiddle3",
			1,
			"LeftHandIndex1",
			1,
			"LeftHandIndex2",
			1,
			"LeftHandIndex3",
			1,
			"LeftHandThumb1",
			1,
			"LeftHandThumb2",
			1,
			"LeftHandThumb3",
			1,
			"RightShoulder",
			1,
			"RightArm",
			1,
			"RightArmRoll",
			1,
			"RightForeArm",
			1,
			"RightForeArmRoll",
			1,
			"RightHand",
			1,
			"RightHandRing",
			1,
			"RightHandPinky1",
			1,
			"RightHandPinky2",
			1,
			"RightHandPinky3",
			1,
			"RightHandRing1",
			1,
			"RightHandRing2",
			1,
			"RightHandRing3",
			1,
			"RightHandMiddle1",
			1,
			"RightHandMiddle2",
			1,
			"RightHandMiddle3",
			1,
			"RightHandIndex1",
			1,
			"RightHandIndex2",
			1,
			"RightHandIndex3",
			1,
			"RightHandThumb1",
			1,
			"RightHandThumb2",
			1,
			"RightHandThumb3",
			1,
			"spine3",
			0.94999999,
			"spine2",
			0.89999998,
			"spine1",
			0.80000001,
			"spine",
			0.69999999
		};
		LeftHandFeed[]=
		{
			"head",
			1,
			"neck1",
			1,
			"neck",
			1,
			"weapon",
			0,
			"LeftShoulder",
			1,
			"LeftArm",
			1,
			"LeftArmRoll",
			1,
			"LeftForeArm",
			1,
			"LeftForeArmRoll",
			1,
			"LeftHand",
			1,
			"LeftHandRing",
			1,
			"LeftHandPinky1",
			1,
			"LeftHandPinky2",
			1,
			"LeftHandPinky3",
			1,
			"LeftHandRing1",
			1,
			"LeftHandRing2",
			1,
			"LeftHandRing3",
			1,
			"LeftHandMiddle1",
			1,
			"LeftHandMiddle2",
			1,
			"LeftHandMiddle3",
			1,
			"LeftHandIndex1",
			1,
			"LeftHandIndex2",
			1,
			"LeftHandIndex3",
			1,
			"LeftHandThumb1",
			1,
			"LeftHandThumb2",
			1,
			"LeftHandThumb3",
			1,
			"RightShoulder",
			0,
			"RightArm",
			0,
			"RightArmRoll",
			0,
			"RightForeArm",
			0,
			"RightForeArmRoll",
			0,
			"RightHand",
			0,
			"RightHandRing",
			0,
			"RightHandPinky1",
			0,
			"RightHandPinky2",
			0,
			"RightHandPinky3",
			0,
			"RightHandRing1",
			0,
			"RightHandRing2",
			0,
			"RightHandRing3",
			0,
			"RightHandMiddle1",
			0,
			"RightHandMiddle2",
			0,
			"RightHandMiddle3",
			0,
			"RightHandIndex1",
			0,
			"RightHandIndex2",
			0,
			"RightHandIndex3",
			0,
			"RightHandThumb1",
			0,
			"RightHandThumb2",
			0,
			"RightHandThumb3",
			0,
			"Spine",
			0,
			"Spine1",
			0,
			"Spine2",
			0,
			"Spine3",
			0,
			"pelvis",
			"MaskStart"
		};
	};
};
